#Activity 11

---


The goal is to learn the concepts of overfitting, underfitting, generalization, and the purpose of splitting a dataset into training set and validation set. I will try to predict if a person make less or more than 50k a year.

In [10]:
import numpy as np
import pandas as pd
from google.colab import files
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt
import random


url = 'https://raw.githubusercontent.com/pango3001/AI/main/project/adult1.csv'

#numpy darray
data = np.genfromtxt(url, delimiter=",", skip_header = True) 

#panda dataframe
dataset = pd.read_csv(url, delimiter=',')
dataset.head()

age  workclass  fnlwgt  ...  hoursPerWeek  country  earnings
0   39          3   77516  ...            40        1         0
1   50          2   83311  ...            13        1         0
2   38          1  215646  ...            40        1         0
3   53          1  234721  ...            40        1         0
4   28          1  338409  ...            40       14         0

[5 rows x 14 columns]

In [11]:
np.set_printoptions(formatter = {'float': '{: 0.1f}'.format})

In [12]:
from tensorflow.python.client import device_lib

device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 3607108861888345024, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 17696420006855953787
 physical_device_desc: "device: XLA_CPU device", name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 12089630592495722423
 physical_device_desc: "device: XLA_GPU device", name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 14640891840
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 623904616612866075
 physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"]

In [13]:
print(dataset.shape)
print('')
print(dataset[0:5])

(32561, 14)

   age  workclass  fnlwgt  ...  hoursPerWeek  country  earnings
0   39          3   77516  ...            40        1         0
1   50          2   83311  ...            13        1         0
2   38          1  215646  ...            40        1         0
3   53          1  234721  ...            40        1         0
4   28          1  338409  ...            40       14         0

[5 rows x 14 columns]


In [14]:
# Shuffling the dataset
dataset = dataset.sample(frac=1).reset_index(drop=True)

# Convert Pandas DataSet to Numpy Array
dataset_np = dataset.values
X = dataset.drop('earnings', axis='columns').values
Y = dataset['earnings'].values

In [15]:
# Index for 30%
index_30percent = int(0.3 * len(dataset_np[:, 0]))
print(index_30percent)

# Split into training and validation
XVALID = X[:index_30percent, :]
YVALID = Y[:index_30percent]
XTRAIN = X[index_30percent:, :]
YTRAIN = Y[index_30percent:]

9768


In [16]:
# Mean normalization
Xmin = XTRAIN.min(axis = 0) 
Xmax = XTRAIN.max(axis = 0) 
mean = XTRAIN.mean(axis = 0)
XTRAIN = (XTRAIN - mean) / (Xmax - Xmin)
XVALID = (XVALID - mean) / (Xmax - Xmin)

# Rescaling
Ymax = YTRAIN.max()
YTRAIN = YTRAIN / Ymax
YVALID = YVALID / Ymax

## normal neural network

In [17]:
model = Sequential()
model.add(Dense(12, input_dim = 13, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [18]:
model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
history = model.fit(XTRAIN, YTRAIN, epochs = 256, batch_size=64, verbose = 1)

Epoch 1/256
357/357 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7623
Epoch 2/256
357/357 [==============================] - 1s 2ms/step - loss: 0.4060 - accuracy: 0.8127
Epoch 3/256
357/357 [==============================] - 1s 2ms/step - loss: 0.3756 - accuracy: 0.8231
Epoch 4/256
357/357 [==============================] - 1s 2ms/step - loss: 0.3554 - accuracy: 0.8334
Epoch 5/256
357/357 [==============================] - 1s 2ms/step - loss: 0.3435 - accuracy: 0.8395
Epoch 6/256
357/357 [==============================] - 1s 2ms/step - loss: 0.3374 - accuracy: 0.8400
Epoch 7/256
357/357 [==============================] - 1s 2ms/step - loss: 0.3337 - accuracy: 0.8439
Epoch 8/256
357/357 [==============================] - 1s 2ms/step - loss: 0.3316 - accuracy: 0.8440
Epoch 9/256
357/357 [==============================] - 1s 2ms/step - loss: 0.3302 - accuracy: 0.8444
Epoch 10/256
357/357 [==============================] - 1s 2ms/step - loss: 0.3295 - accura

In [19]:
np.set_printoptions(precision = 2)
print ('True Data:')
print(YTRAIN[:10])

prediction = model.predict(XVALID)
Accuracy_normal = abs(YVALID - prediction)

print ('Prediction:')
print (prediction[:10].T)

print ('Accuracy_normal:')
print(Accuracy_normal.flatten())

True Data:
[1. 1. 1. 0. 0. 0. 1. 0. 0. 0.]
Prediction:
[[0.72 0.7  0.39 0.21 0.46 0.04 0.03 0.39 0.51 0.73]]
Accuracy_normal:
[0.28 0.28 0.72 ... 0.13 0.13 0.13]


## UNDERFIT NN




In [20]:
model_0 = Sequential()
model_0.add(Dense(12, input_dim = 13, activation='relu'))
model_0.add(Dense(8, activation='relu'))
model_0.add(Dense(1, activation='sigmoid'))

In [21]:
model_0.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [22]:
history1 = model_0.fit(XTRAIN, YTRAIN, epochs = 2, batch_size=100, verbose = 1)

Epoch 1/2
228/228 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7551
Epoch 2/2
228/228 [==============================] - 1s 2ms/step - loss: 0.4222 - accuracy: 0.7817


In [23]:
np.set_printoptions(precision = 2)
print ('True Data:')
print(YTRAIN[:10])

prediction = model_0.predict(XVALID)
Accuracy_underfit = abs(YVALID - prediction)

print ('Prediction:')
print (prediction[:10].T)

print ('Accuracy_underfit:')
print(Accuracy_underfit.flatten())

True Data:
[1. 1. 1. 0. 0. 0. 1. 0. 0. 0.]
Prediction:
[[0.55 0.54 0.55 0.29 0.4  0.24 0.29 0.58 0.46 0.34]]
Accuracy_underfit:
[0.45 0.45 0.55 ... 0.29 0.29 0.29]


## OVERFIT NN


In [24]:
model1 = Sequential()
model1.add(Dense(120, input_dim = 13, activation='relu'))
model1.add(Dense(80, activation='relu'))
model1.add(Dense(1, activation='sigmoid'))

In [25]:
model1.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
history2 = model1.fit(XTRAIN, YTRAIN, epochs = 2048, batch_size=100, verbose = 1)

Epoch 1/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.4245 - accuracy: 0.8011
Epoch 2/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.3405 - accuracy: 0.8410
Epoch 3/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.3307 - accuracy: 0.8459
Epoch 4/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.3267 - accuracy: 0.8475
Epoch 5/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.3257 - accuracy: 0.8464
Epoch 6/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.3245 - accuracy: 0.8478
Epoch 7/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.3221 - accuracy: 0.8492
Epoch 8/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.3214 - accuracy: 0.8495
Epoch 9/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.3210 - accuracy: 0.8499
Epoch 10/2048
228/228 [==============================] - 1s 2ms/step - loss: 0.320

In [26]:
np.set_printoptions(precision = 2)
print ('True Data:')
print(YTRAIN[:10])

prediction = model1.predict(XVALID)
Accuracy_Overfit = abs(YVALID - prediction)

print ('Prediction:')
print (prediction[:10].T)

print ('Accuracy_Overfit:')
print(Accuracy_Overfit.flatten())

True Data:
[1. 1. 1. 0. 0. 0. 1. 0. 0. 0.]
Prediction:
[[5.79e-01 9.52e-01 7.84e-03 2.98e-06 1.31e-01 9.39e-08 1.63e-11 2.49e-01
  2.31e-02 9.93e-01]]
Accuracy_Overfit:
[4.21e-01 4.21e-01 5.79e-01 ... 2.63e-06 2.63e-06 2.63e-06]


## Comparing the 3


In [27]:
print ('Accuracy_normal:')
print(Accuracy_normal[:10, 1].flatten())

print ('Accuracy_underfit:')
print(Accuracy_underfit[:10, 1].flatten())

print ('Accuracy_Overfit:')
print(Accuracy_Overfit[:10, 1].flatten())

Accuracy_normal:
[0.28 0.3  0.61 0.79 0.54 0.96 0.97 0.61 0.49 0.27]
Accuracy_underfit:
[0.45 0.46 0.45 0.71 0.6  0.76 0.71 0.42 0.54 0.66]
Accuracy_Overfit:
[0.42 0.05 0.99 1.   0.87 1.   1.   0.75 0.98 0.01]


1: Overtraining allows for noise to be amplified during the training of the NN.

2:
Overfitting= validation loss levels out then start to increase while training loss continues to decrease

Underfitting= stopping too early

Generalization= validation loss and training loss continue to decrease with a small difference between the two rates (that is normal). Training does not go on for too long or too short.

3: normalizing the training data seperately from the validation allows for the two seperated data sets not to be affected by each other.

