#Activity 11

---


The goal is to learn the concepts of overfitting, underfitting, generalization, and the purpose of splitting a dataset into training set and validation set. I will try to predict if a person make less or more than 50k a year.

In [1]:
import numpy as np
import pandas as pd
from google.colab import files
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt
import random


url = 'https://raw.githubusercontent.com/pango3001/AI/main/project/adult1.csv'

#numpy darray
data = np.genfromtxt(url, delimiter=",", skip_header = True) 

#panda dataframe
dataset = pd.read_csv(url, delimiter=',')
dataset.head()

age  workclass  fnlwgt  ...  hoursPerWeek  country  earnings
0   39          3   77516  ...            40        1         0
1   50          2   83311  ...            13        1         0
2   38          1  215646  ...            40        1         0
3   53          1  234721  ...            40        1         0
4   28          1  338409  ...            40       14         0

[5 rows x 14 columns]

In [2]:
np.set_printoptions(formatter = {'float': '{: 0.1f}'.format})

In [3]:
print('')
print(dataset.shape)
print('')
print(dataset[0:5])


(32561, 14)

   age  workclass  fnlwgt  ...  hoursPerWeek  country  earnings
0   39          3   77516  ...            40        1         0
1   50          2   83311  ...            13        1         0
2   38          1  215646  ...            40        1         0
3   53          1  234721  ...            40        1         0
4   28          1  338409  ...            40       14         0

[5 rows x 14 columns]


In [4]:
# Shuffling the dataset
dataset = dataset.sample(frac=1).reset_index(drop=True)

# Convert Pandas DataSet to Numpy Array
dataset_np = dataset.values
X = dataset.drop('earnings', axis='columns').values
Y = dataset['earnings'].values

In [5]:
# Index for 30%
index_30percent = int(0.3 * len(dataset_np[:, 0]))
print(index_30percent)

# Split into training and validation
XVALID = X[:index_30percent, :]
YVALID = Y[:index_30percent]
XTRAIN = X[index_30percent:, :]
YTRAIN = Y[index_30percent:]

9768


In [6]:
# Mean normalization
Xmin = XTRAIN.min(axis = 0) 
Xmax = XTRAIN.max(axis = 0) 
mean = XTRAIN.mean(axis = 0)
XTRAIN = (XTRAIN - mean) / (Xmax - Xmin)
XVALID = (XVALID - mean) / (Xmax - Xmin)

# Rescaling
Ymax = YTRAIN.max()
YTRAIN = YTRAIN / Ymax
YVALID = YVALID / Ymax

## normal neural network

In [9]:
model = Sequential()
model.add(Dense(12, input_dim = 13, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [10]:
model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
history = model.fit(XTRAIN, YTRAIN, epochs = 256, batch_size=64, verbose = 1)

Epoch 1/256
357/357 [==============================] - 1s 3ms/step - loss: 0.5080 - accuracy: 0.7709
Epoch 2/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3910 - accuracy: 0.8195
Epoch 3/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3621 - accuracy: 0.8321
Epoch 4/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3437 - accuracy: 0.8403
Epoch 5/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3358 - accuracy: 0.8431
Epoch 6/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3324 - accuracy: 0.8455
Epoch 7/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3304 - accuracy: 0.8477
Epoch 8/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3290 - accuracy: 0.8483
Epoch 9/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3282 - accuracy: 0.8470
Epoch 10/256
357/357 [==============================] - 1s 3ms/step - loss: 0.3271 - accura

In [11]:
np.set_printoptions(precision = 2)
print ('True Data:')
print(YTRAIN[:10])

prediction = model.predict(XVALID)
MSE = abs(YVALID - prediction)

print ('Prediction:')
print (prediction[:10].T)

print ('Accuracy_normal:')
print(Accuracy_normal.flatten())

True Data:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Prediction:
[[7.34e-01 5.76e-01 1.09e-01 7.01e-03 7.84e-01 8.05e-03 7.35e-03 1.64e-02
  6.78e-04 3.06e-03]]
MSE:
[0.27 0.73 0.73 ... 0.2  0.2  0.2 ]


## UNDERFIT NN




In [12]:
model_0 = Sequential()
model_0.add(Dense(12, input_dim = 13, activation='relu'))
model_0.add(Dense(8, activation='relu'))
model_0.add(Dense(1, activation='sigmoid'))

In [13]:
model_0.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])



In [14]:
history1 = model_0.fit(XTRAIN, YTRAIN, epochs = 2, batch_size=100, verbose = 1)

Epoch 1/2
228/228 [==============================] - 1s 3ms/step - loss: 0.5453 - accuracy: 0.7343
Epoch 2/2
228/228 [==============================] - 1s 3ms/step - loss: 0.4316 - accuracy: 0.7811


In [15]:
np.set_printoptions(precision = 2)
print ('True Data:')
print(YTRAIN[:10])

prediction = model_0.predict(XVALID)
Accuracy_underfit = abs(YVALID - prediction)

print ('Prediction:')
print (prediction[:10].T)

print ('Accuracy_underfit:')
print(Accuracy_underfit.flatten())

True Data:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Prediction:
[[0.55 0.54 0.13 0.05 0.56 0.05 0.03 0.21 0.05 0.04]]
MSEU:
[0.45 0.55 0.55 ... 0.2  0.2  0.2 ]


## OVERFIT NN


In [16]:
model1 = Sequential()
model1.add(Dense(120, input_dim = 13, activation='relu'))
model1.add(Dense(80, activation='relu'))
model1.add(Dense(1, activation='sigmoid'))

In [ ]:
model1.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
history2 = model1.fit(XTRAIN, YTRAIN, epochs = 2048, batch_size=100, verbose = 1)

Epoch 1/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.4197 - accuracy: 0.8047
Epoch 2/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.3426 - accuracy: 0.8398
Epoch 3/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.3304 - accuracy: 0.8458
Epoch 4/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.3269 - accuracy: 0.8474
Epoch 5/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.3244 - accuracy: 0.8497
Epoch 6/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.3237 - accuracy: 0.8498
Epoch 7/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.3216 - accuracy: 0.8502
Epoch 8/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.3206 - accuracy: 0.8490
Epoch 9/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.3203 - accuracy: 0.8521
Epoch 10/2048
228/228 [==============================] - 1s 3ms/step - loss: 0.318

In [ ]:
np.set_printoptions(precision = 2)
print ('True Data:')
print(YTRAIN[:10])

prediction = model1.predict(XVALID)
Accuracy_Overfit = abs(YVALID - prediction)

print ('Prediction:')
print (prediction[:10].T)

print ('Accuracy_Overfit:')
print(Accuracy_Overfit.flatten())

## Comparing the 3


In [ ]:
print ('Accuracy_normal:')
print(Accuracy_normal[:10, 1].flatten())

print ('Accuracy_underfit:')
print(Accuracy_underfit[:10, 1].flatten())

print ('Accuracy_Overfit:')
print(Accuracy_Overfit[:10, 1].flatten())

1: Overtraining allows for noise to be amplified during the training of the NN.

2:
Overfitting= validation loss levels out then start to increase while training loss continues to decrease

Underfitting= stopping too early

Generalization= validation loss and training loss continue to decrease with a small difference between the two rates (that is normal). Training does not go on for too long or too short.

3: normalizing the training data seperately from the validation allows for the two seperated data sets not to be affected by each other.

